image: docker:19.03.12
services:
  - docker:19.03.12-dind

stages:
  - build

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - "echo \"//TODO: Add steps\""