image: docker:20.10
services:
  - docker:20.10-dind

stages:
  - build

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - "echo \"//TODO: Add steps\""